# Generated by Django 2.1.7 on 2019-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='模板名称')),
                ('font', models.CharField(max_length=5, verbose_name='字体代码')),
                ('fontsize', models.IntegerField(verbose_name='字体大小')),
                ('img', models.ImageField(upload_to='pyq_tool', verbose_name='模板图片')),
                ('imgsize', models.CharField(max_length=10, verbose_name='图片大小')),
                ('icon', models.ImageField(upload_to='pyq_tool', verbose_name='图标')),
                ('hint', models.CharField(max_length=10, verbose_name='输入提示')),
                ('textcolor', models.CharField(max_length=15, verbose_name='文本颜色')),
                ('textplace', models.CharField(max_length=10, verbose_name='文本位置')),
                ('text2', models.CharField(blank=True, max_length=15, null=True, verbose_name='日期文本')),
                ('text2hint', models.CharField(blank=True, max_length=10, null=True, verbose_name='文本2提示')),
                ('text2place', models.CharField(blank=True, max_length=10, null=True, verbose_name='日期位置')),
            ],
            options={
                'verbose_name': '票圈神器',
                'verbose_name_plural': '票圈神器',
            },
        ),
    ]
